export const categoryDetails = {
  'cartes-nfc': {
    size: '85.5 x 54 mm',
  },
  'stickers-nfc': {
    size: '85 mm',
  },
  'tags-nfc': {
    size: '12 x 12 cm',
  },
  'presentoirs-nfc': {
    size: 'A6 - 105 x 148 mm',
  },
  'chevalets-nfc': {
    size: '127 x 76 mm',
  },
};

export const volumeDiscounts = [
  {
    quantity: 2,
    discount: 10,
    savingsDhs: 70,
  },
  {
    quantity: 3,
    discount: 15,
    savingsDhs: 157.50,
  },
  {
    quantity: 5,
    discount: 20,
    savingsDhs: 349.90,
  },
  {
    quantity: 10,
    discount: 25,
    savingsDhs: 874.80,
  },
  {
    quantity: 15,
    discount: 30,
    savingsDhs: 1574.60,
  },
];

export const categories = [
  {
    id: 'cartes-nfc',
    name: 'Cartes NFC',
    products: [
      {
        id: 1,
        name: "Carte d'avis Google",
        description: "Carte NFC intelligente pour collecter facilement les avis Google. Augmentez votre visibilité et votre réputation en ligne.",
        originalPrice: '299 Dhs',
        price: '199 Dhs',
        images: [
          'https://imgur.com/DtQ8yZU.png',
          'https://imgur.com/K2GvaNY.png',
          'https://imgur.com/z1tKyOa.png',
          'https://imgur.com/ZmkHNb4.png',
        ],
        type: 'google',
        customLabel: 'Lien ou nom de votre page Google',
      },
      {
        id: 2,
        name: 'Carte YouTube Creator',
        description: 'Carte NFC intelligente pour les créateurs YouTube. Partagez instantanément votre chaîne et connectez-vous avec vos abonnés.',
        originalPrice: '299 Dhs',
        price: '199 Dhs',
        images: [
          'https://imgur.com/h1pUrJS.png',
          'https://imgur.com/eqpwx1U.png',
          'https://imgur.com/mIb0eFh.png',
          'https://imgur.com/tV35Kfc.png',
        ],
        type: 'youtube',
        customLabel: 'Lien vers votre chaîne YouTube',
      },
      {
        id: 3,
        name: 'Carte WhatsApp Contact',
        description: 'Carte de contact WhatsApp intelligente avec partage instantané.',
        originalPrice: '299 Dhs',
        price: '199 Dhs',
        images: [
          'https://imgur.com/SisVeFk.png',
          'https://imgur.com/kP6M1zv.png',
          'https://imgur.com/V0TmgFF.png',
          'https://imgur.com/TXlHSZy.png',
        ],
        type: 'whatsapp',
        customLabel: 'Précisez votre numéro WhatsApp',
      },
      {
        id: 4,
        name: 'Carte Facebook Follow',
        description: 'Carte NFC intelligente pour votre page Facebook. Augmentez votre visibilité et connectez-vous avec vos followers.',
        originalPrice: '299 Dhs',
        price: '199 Dhs',
        images: [
          'https://imgur.com/BcSvJ2C.png',
          'https://imgur.com/JJBzHK4.png',
          'https://imgur.com/OZ2iGaw.png',
          'https://imgur.com/6OjKtJQ.png',
        ],
        type: 'facebook',
        customLabel: 'Lien vers votre page Facebook',
      },
      {
        id: 5,
        name: 'Carte Snapchat Follow',
        description: 'Carte NFC intelligente pour votre profil Snapchat. Augmentez vos followers et partagez vos stories instantanément.',
        originalPrice: '299 Dhs',
        price: '199 Dhs',
        images: [
          'https://imgur.com/LXIXGAo.png',
          'https://imgur.com/S86HuvI.png',
          'https://imgur.com/i2OVac4.png',
          'https://imgur.com/MsxaSYR.png',
        ],
        type: 'snapchat',
        customLabel: 'Lien de profil Snapchat',
      },
      {
        id: 6,
        name: 'Carte Instagram Follow',
        description: 'Carte NFC intelligente pour votre profil Instagram. Augmentez vos followers et partagez votre contenu instantanément.',
        originalPrice: '299 Dhs',
        price: '199 Dhs',
        images: [
          'https://imgur.com/Z9PAb3u.png',
          'https://imgur.com/tsmVG9N.png',
          'https://imgur.com/cSAueVz.png',
          'https://imgur.com/3rkODJv.png',
          'https://imgur.com/huc5ON2.png',
        ],
        type: 'instagram',
        customLabel: 'Lien vers votre page Instagram',
      },
      {
        id: 7,
        name: 'Carte TikTok Follow',
        description: 'Carte NFC intelligente pour votre profil TikTok. Augmentez vos followers et partagez vos vidéos virales instantanément.',
        originalPrice: '299 Dhs',
        price: '199 Dhs',
        images: [
          'https://imgur.com/vr9Kr62.png',
          'https://imgur.com/0Y1IA0J.png',
          'https://imgur.com/FRP4kTx.png',
          'https://imgur.com/fd3ogny.png',
          'https://imgur.com/shO33CY.png',
        ],
        type: 'tiktok',
        customLabel: 'Lien vers votre page TikTok',
      },
      {
        id: 8,
        name: 'Carte NFC Personnalisable',
        description: 'Créez votre carte NFC unique avec votre propre design. Une solution personnalisée pour votre marque ou votre entreprise.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/r18S7v8.png',
          'https://imgur.com/wLIYruw.png',
          'https://imgur.com/gFD2yth.png',
          'https://imgur.com/t7Pd6Di.png',
        ],
        type: 'custom',
        customLabel: 'Appuyez sur Commander via WhatsApp et envoyez-nous votre design là-bas',
      },
    ],
  },
  {
    id: 'stickers-nfc',
    name: 'Stickers NFC',
    products: [
      {
        id: 'sticker-facebook',
        name: 'Sticker NFC Facebook pour mur, comptoir, point de vente et vitrine',
        description: 'Sticker NFC intelligent pour promouvoir votre présence Facebook.',
        originalPrice: '199 Dhs',
        price: '99 Dhs',
        images: [
          'https://imgur.com/YCeoXen.png',
          'https://imgur.com/hsDpWuL.png',
          'https://imgur.com/77xZvxM.png',
          'https://imgur.com/u1iNLkd.png',
        ],
        type: 'facebook',
        customLabel: "Spécifiez l'URL ou le nom d'utilisateur de votre page Facebook",
      },
      {
        id: 'sticker-whatsapp',
        name: 'Sticker NFC WhatsApp pour mur, comptoir, point de vente et vitrine',
        description: 'Sticker NFC intelligent pour faciliter le contact WhatsApp.',
        originalPrice: '199 Dhs',
        price: '99 Dhs',
        images: [
          'https://imgur.com/DVKnQFx.png',
          'https://imgur.com/OTmVUsY.png',
          'https://imgur.com/4FQEagP.png',
          'https://imgur.com/fvorOyD.png',
        ],
        type: 'whatsapp',
        customLabel: 'Indiquez votre numéro de téléphone WhatsApp',
      },
      {
        id: 'sticker-google',
        name: 'Sticker NFC Avis connecté Google pour mur, comptoir, point de vente et vitrine',
        description: 'Sticker NFC intelligent pour collecter les avis Google.',
        originalPrice: '199 Dhs',
        price: '99 Dhs',
        images: [
          'https://imgur.com/lDptHrQ.png',
          'https://imgur.com/2s0aUjR.png',
          'https://imgur.com/LmRFyP4.png',
          'https://imgur.com/D2kTb4g.png',
        ],
        type: 'google',
        customLabel: "Précisez l'URL ou le nom de votre page Google My Business",
      },
      {
        id: 'sticker-restaurant',
        name: 'Sticker NFC Restaurant pour mur, comptoir, point de vente et vitrine',
        description: 'Sticker NFC intelligent pour restaurants et établissements.',
        originalPrice: '199 Dhs',
        price: '99 Dhs',
        images: [
          'https://imgur.com/OlcDihz.png',
          'https://imgur.com/rn2dYLJ.png',
          'https://imgur.com/Pb5JuCR.png',
          'https://imgur.com/PqfN82Z.png',
        ],
        type: 'restaurant',
        customLabel: 'Spécifiez l\'URL de votre site Web ou de votre menu ou le lien Google des avis',
      },
    ],
  },
  {
    id: 'tags-nfc',
    name: 'Tags NFC',
    products: [
      {
        id: 'plaque-rdv',
        name: 'Plaque NFC Rendez-Vous connectée pour mur, comptoir, PLV et vitrine',
        description: 'Plaque NFC intelligente pour faciliter la prise de rendez-vous.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/z1d2xDX.png',
          'https://imgur.com/UuyvWbF.png',
          'https://imgur.com/wAOA8TQ.png',
          'https://imgur.com/C9oEsFV.png',
        ],
        type: 'calendar',
        customLabel: "Spécifiez l'URL de votre calendrier",
      },
      {
        id: 'plaque-google',
        name: 'Avis clients Google Plaque NFC pour mur, comptoir, PLV et vitrine',
        description: 'Plaque NFC intelligente pour collecter les avis Google.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/FIQmfuZ.png',
          'https://imgur.com/VeYZIyo.png',
          'https://imgur.com/Nh7Ee94.png',
        ],
        type: 'google',
        customLabel: 'Précisez le lien ou le nom de votre page Google My Business',
      },
      {
        id: 'plaque-location',
        name: 'Plaque NFC Location de voiture connectée pour mur, comptoir, PLV et vitrine',
        description: 'Plaque NFC intelligente pour sociétés de location de véhicules.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/qjDMYdS.png',
          'https://imgur.com/wEGgyxm.png',
          'https://imgur.com/XZxeNoL.png',
        ],
        type: 'rental',
        customLabel: 'Indiquez l\'URL de votre site ou le lien des avis Google',
      },
      {
        id: 'plaque-restaurant',
        name: 'Plaque NFC Restaurant pour mur, comptoir, PLV et vitrine',
        description: 'Plaque NFC intelligente pour restaurants et établissements.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/AFJEtJz.png',
          'https://imgur.com/mpU0O4h.png',
          'https://imgur.com/8M122NP.png',
        ],
        type: 'restaurant',
        customLabel: 'Spécifiez l\'URL de votre site ou de votre menu ou le lien des avis Google',
      },
      {
        id: 'plaque-custom',
        name: 'Plaque NFC personnalisable',
        description: 'Créez votre plaque NFC unique avec votre propre design.',
        originalPrice: '499 Dhs',
        price: '399 Dhs',
        images: [
          'https://imgur.com/ZjRNdmM.png',
          'https://imgur.com/odb8nv9.png',
          'https://imgur.com/E2AUEiP.png',
          'https://imgur.com/qvr6sU2.png',
        ],
        type: 'custom',
        customLabel: 'envoyez-nous votre design sur WhatsApp',
      },
    ],
  },
  {
    id: 'presentoirs-nfc',
    name: 'Présentoirs NFC',
    products: [
      {
        id: 'presentoir-google',
        name: 'Affichage des avis Google avec NFC et code QR (recto verso)',
        description: 'Présentoir NFC intelligent pour collecter les avis Google.',
        originalPrice: '499 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/w07d1aZ.png',
          'https://imgur.com/pjzrkYD.png',
          'https://imgur.com/kqkeZCP.png',
        ],
        type: 'google',
        customLabel: 'Veuillez préciser le lien vers votre page Google.',
      },
      {
        id: 'presentoir-facebook',
        name: 'Affichage NFC et QR Code Facebook (recto verso)',
        description: 'Présentoir NFC intelligent pour promouvoir votre présence Facebook.',
        originalPrice: '499 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/nPhOmXr.png',
          'https://imgur.com/Gy77ON5.png',
          'https://imgur.com/cmgnbd7.png',
        ],
        type: 'facebook',
        customLabel: 'Précisez le lien vers votre page Facebook.',
      },
      {
        id: 'presentoir-location',
        name: 'Affichage NFC et QR Code pour agence de location de voiture (recto verso)',
        description: 'Présentoir NFC intelligent pour agences de location de voitures.',
        originalPrice: '499 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/oxvHsKq.png',
          'https://imgur.com/tEqR4wv.png',
          'https://imgur.com/mcIBXXF.png',
          'https://imgur.com/kadd0pQ.png',
        ],
        type: 'rental',
        customLabel: 'Spécifiez le lien vers votre site Web, le lien des avis Google ou une page spécifique.',
      },
      {
        id: 'presentoir-restaurant',
        name: 'lien vers le site Web du restaurant ou lien vers les avis Google (recto verso)',
        description: 'Présentoir NFC intelligent pour restaurants et établissements.',
        originalPrice: '499 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/86OTM6d.png',
          'https://imgur.com/T7mEXXV.png',
          'https://imgur.com/NaDDLWy.png',
        ],
        type: 'restaurant',
        customLabel: 'Spécifiez le lien vers votre site Web ou une page spécifique.',
      },
      {
        id: 'presentoir-rdv',
        name: 'Affichage de rendez-vous NFC et QR code (recto verso)',
        description: 'Présentoir NFC intelligent pour la prise de rendez-vous.',
        originalPrice: '499 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/d1tZ93g.png',
          'https://imgur.com/TDQdmXx.png',
          'https://imgur.com/kRjlqHt.png',
        ],
        type: 'calendar',
        customLabel: 'Veuillez fournir le lien vers votre site Web ou une page spécifique.',
      },
    ],
  },
  {
    id: 'chevalets-nfc',
    name: 'Chevalets NFC',
    products: [
      {
        id: 'chevalet-google',
        name: 'Chevalet NFC Google Review 2 en 1 avec QR code',
        description: 'Chevalet NFC intelligent pour collecter les avis Google de vos clients.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/bsw1NEe.png',
          'https://imgur.com/6bMFZRl.png',
        ],
        type: 'google',
        customLabel: 'Spécifiez le lien vers votre page Google',
      },
      {
        id: 'chevalet-facebook',
        name: 'Chevalet NFC Facebook avec puce NFC et QR code',
        description: 'Chevalet NFC intelligent pour promouvoir votre présence Facebook.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/tryEU4C.png',
          'https://imgur.com/DLEXEyV.png',
        ],
        type: 'facebook',
        customLabel: 'Spécifiez le lien vers votre page Facebook.',
      },
      {
        id: 'chevalet-web',
        name: 'Chevalet de site Web NFC avec puce NFC et code QR',
        description: 'Chevalet NFC intelligent pour promouvoir votre site web.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/QodeMjF.png',
          'https://imgur.com/xEzdVsV.png',
        ],
        type: 'website',
        customLabel: 'Spécifiez le lien de votre site Web.',
      },
      {
        id: 'chevalet-wifi',
        name: 'Chevalet Wifi NFC avec puce NFC et QR code',
        description: 'Chevalet NFC intelligent pour partager facilement vos informations WiFi.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/9X2DLqn.png',
          'https://imgur.com/S98vrGC.png',
        ],
        type: 'wifi',
        customLabel: 'Name and password of your Wifi.',
      },
      {
        id: 'chevalet-youtube',
        name: 'Chevalet NFC YouTube avec puce NFC et QR code',
        description: 'Chevalet NFC intelligent pour promouvoir votre chaîne YouTube.',
        originalPrice: '399 Dhs',
        price: '299 Dhs',
        images: [
          'https://imgur.com/kSyorVZ.png',
          'https://imgur.com/YGXbUpj.png',
        ],
        type: 'youtube',
        customLabel: 'Spécifiez le lien vers votre page YouTube.',
      },
    ],
  },
];